// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _13_ORM_Geenid.Data;

#nullable disable

namespace _13_ORM_Geenid.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("_13_ORM_Geenid.Models.Alleeli", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nimetus")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Positiivne")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Nimetus");

                    b.ToTable("Alleelid");
                });

            modelBuilder.Entity("_13_ORM_Geenid.Models.Geeni", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Alleel1Id")
                        .HasColumnType("int");

                    b.Property<int>("Alleel2Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Alleel1Id");

                    b.HasIndex("Alleel2Id");

                    b.ToTable("Geenid");
                });

            modelBuilder.Entity("_13_ORM_Geenid.Models.Geeni", b =>
                {
                    b.HasOne("_13_ORM_Geenid.Models.Alleeli", "Alleel1")
                        .WithMany()
                        .HasForeignKey("Alleel1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("_13_ORM_Geenid.Models.Alleeli", "Alleel2")
                        .WithMany()
                        .HasForeignKey("Alleel2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Alleel1");

                    b.Navigation("Alleel2");
                });
#pragma warning restore 612, 618
        }
    }
}
